---
- name: Hypervisor base configuration
  hosts: hypervisor
  become: true
  gather_facts: false

  tasks:
    # --- Phase 1: Assert authoritative identity ---
    - name: Set permanent hostname
      ansible.builtin.hostname:
        name: "{{ hypervisor_hostname }}"

    # --- Phase 2: Assert authoritative SSH daemon policy ---
    - name: Enforce SSH daemon configuration (authoritative)
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        create: false
        marker: "# {mark} ANSIBLE MANAGED SSH POLICY"
        block: |
          PasswordAuthentication no
          PermitRootLogin no
          PubkeyAuthentication yes
          UsePAM yes
      notify: Reload sshd
    - name: Ensure automation user exists
      ansible.builtin.user:
        name: svc-ansible
        comment: "Automation User"
        shell: /bin/bash
        state: present
        create_home: yes
        groups: sudo
        append: yes
    - name: Ensure automation user has passwordless sudo
      ansible.builtin.copy:
        dest: /etc/sudoers.d/svc-ansible
        content: |
          svc-ansible ALL=(ALL) NOPASSWD: ALL
        owner: root
        group: root
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'


  handlers:
    - name: Reload sshd
      ansible.builtin.service:
        name: ssh
        state: reloaded