---
- name: Hypervisor base configuration
  hosts: hypervisor
  become: true
  gather_facts: false

  tasks:
    # --- Phase 1: Assert authoritative identity ---
    - name: Set permanent hostname
      ansible.builtin.hostname:
        name: "{{ hypervisor_hostname }}"

    # --- Phase 2: Assert authoritative SSH daemon policy ---
    - name: Enforce SSH daemon configuration (authoritative)
      ansible.builtin.blockinfile:
        path: /etc/ssh/sshd_config
        create: false
        marker: "# {mark} ANSIBLE MANAGED SSH POLICY"
        block: |
          PasswordAuthentication no
          PermitRootLogin no
          PubkeyAuthentication yes
          UsePAM yes
      notify: Reload sshd
    # --- Phase 3: Assert automation user exists and has sudo ---
    - name: Ensure automation user exists
      ansible.builtin.user:
        name: svc-ansible
        comment: "Automation User"
        shell: /bin/bash
        state: present
        create_home: yes
        groups: sudo
        append: yes
    - name: Ensure automation user has passwordless sudo
      ansible.builtin.copy:
        dest: /etc/sudoers.d/svc-ansible
        content: |
          svc-ansible ALL=(ALL) NOPASSWD: ALL
        owner: root
        group: root
        mode: '0440'
        validate: '/usr/sbin/visudo -cf %s'
    # --- Phase 4: Assert authoritative timezone ---
    - name: Set system timezone
      ansible.builtin.timezone:
        name: "{{ hypervisor_timezone }}"
    # --- Phase 5: Assert SSH Authorized Keys for Automation User ---
    - name: Ensure SSH authorized keys for automation user
      ansible.builtin.authorized_key:
        user: svc-ansible
        state: present
        key: "{{ lookup('file', 'files/ssh_keys/id_svc-ansible.pub') }}"
    # --- Phase 6: Assert baseline packages are installed ---
    - name: Ensure baseline packages are installed
      ansible.builtin.package:
        name:
          - vim
          - curl
          - sudo
          - ca-certificates
          - openssh-server
        state: present
    


  handlers:
    - name: Reload sshd
      ansible.builtin.service:
        name: ssh
        state: reloaded