---
- name: Hypervisor base configuration
  hosts: hypervisor
  become: true
  gather_facts: false
  roles:
    - identity
    - baseline
    - security
    - role: networkd
      tags:
        - never
        - networking
    - role: hypervisor-networking
      tags:
        - never
        - networking
    - role: kvm
      tags:
        - kvm
